apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: content-web
  name: content-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: content-web
    spec:
      containers:
      - image: famedical.azurecr.io/content-web:v1
        name: conent-web
        resources:
          requests:
            memory: "128M"
            cpu: "0.5"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: content-web
  name: content-web
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
  selector:
    app: content-web
  type: LoadBalancer
status:
  loadBalancer: {}