apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: content-api
  name: content-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: content-api
    spec:
      containers:
      - image: famedical.azurecr.io/content-api:v2
        name: conent-api
        env:
          - name: MONGODB_CONNECTION
            value: "mongodb://mongodb:27017/contentdb"
        resources:
           requests:
              memory: "128M"
              cpu: "0.5"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: content-api
  name: content-api
spec:
  ports:
  - name: "3001"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: content-api
  type: ClusterIP
status:
  loadBalancer: {}