apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: famedical-db
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 5Gi

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: famedical-config
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 5Gi